# Generated by Django 5.0.6 on 2026-09-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
