# Generated by Django 5.0.6 on 2026-09-03 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_labour_aadhaar_number_labour_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='location',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='trade',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of skills/trades (e.g., Mason, Carpenter)', size=None),
        ),
    ]
