# Generated by Django 5.0.6 on 2026-09-05 12:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
