# Generated by Django 5.0.6 on 2026-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pagecontent_content_alter_pagecontent_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS (injected into <head>)')),
                ('custom_js', models.TextField(blank=True, help_text='Custom JavaScript (injected at bottom of page)')),
                ('header_html', models.TextField(blank=True, help_text='Extra HTML/JS to render inside the header (e.g., a banner)')),
                ('footer_html', models.TextField(blank=True, help_text='Extra HTML/JS to render inside the footer (e.g., social icons)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
