# Generated by Django 5.0.6 on 2026-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='custom_js',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_html',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_html',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='body_end_html',
            field=models.TextField(blank=True, help_text='HTML/JS to inject at the very bottom of the page, after the footer (e.g., LiveChat widgets).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='head_html',
            field=models.TextField(blank=True, help_text='HTML/CSS/JS to inject inside <head> (e.g., meta tags, Google Analytics, custom CSS).'),
        ),
    ]
