# Generated by Django 5.0.6 on 2026-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_sitesettings_custom_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
